#!/usr/bin/env python3
"""
JP Travel Bali — v10 발리 11개 지역 데이터
Google Helpful Content 대응: 구체적 장소·가격·주소·전화번호 포함
"""

BALI_DATA = {
    "우붓": {
        "desc": "발리 문화예술의 중심지",
        "vibe": "예술가 마을",
        "character": "우붓은 발리에서 가장 예술적인 도시예요. 거리마다 미술관과 공방이 있고, 사원에서 전통 공연이 열려요.",
        "transport_tip": "공항에서 90분, 그랩 300,000Rp. 우붓 시내는 스쿠터 80,000Rp/일",
        "best_time": "오전 8시~11시",
        "best_season": "4~10월 건기",
        "hidden": "캄포한 리지 절벽 위 산책로는 우붓 시내에서 도보 15분인데 관광객이 거의 없어요",
        "spots": ["테갈랑 라이스 테라스", "원숭이 숲", "우붓 아트 마켓", "타만 사라스와티 사원", "캄포한 리지"],
        "airport_min": 90,
        "food": [
            {"name": "Bebek Bengil (Dirty Duck Diner)", "price": "95,000Rp", "krw": "약 9,500원", "tip": "우붓 대표 오리구이. 바삭한 크리스피덕이 시그니처. 예약 필수", "area": "우붓 시내", "must": "크리스피덕 세트", "addr": "Jl. Hanoman, Padang Tegal, Ubud", "phone": "+62 361 975 489"},
            {"name": "Warung Babi Guling Ibu Oka", "price": "50,000Rp", "krw": "약 5,000원", "tip": "새끼돼지구이. 오전에 가야 sold out 안됨", "area": "우붓 궁전 근처", "must": "바비굴링 스페셜", "addr": "Jl. Suweta, Taman, Ubud", "phone": "+62 361 976 345"},
            {"name": "Clear Cafe", "price": "음료 40,000~80,000Rp", "krw": "약 4,000~8,000원", "tip": "강변 뷰 카페. 비건 메뉴도 있음", "area": "캠프한 리지", "must": "스무디볼", "addr": "Jl. Raya Campuhan, Ubud"},
            {"name": "Locavore", "price": "점심 350,000Rp~", "krw": "약 35,000원~", "tip": "발리 최고 파인다이닝. 2개월 전 예약 필요", "area": "우붓 시내", "must": "코스 요리", "addr": "Jl. Dewisita No.10, Ubud", "phone": "+62 361 977 733"},
            {"name": "Room 4 Dessert", "price": "디저트 120,000~200,000Rp", "krw": "약 12,000~20,000원", "tip": "디저트 바. 예약 추천", "area": "우붓 시내", "must": "코스 디저트", "addr": "Jl. Raya Sanggingan, Ubud"},
            {"name": "Sayuri Healing Food", "price": "브런치 60,000~120,000Rp", "krw": "약 6,000~12,000원", "tip": "비건 전문. 건강식 선호자에게 추천", "area": "우붓 시내", "must": "스무디볼", "addr": "Jl. Hanoman, Ubud"},
        ],
        "culture": [
            {"name": "타만 사라스와티 사원", "price": "무료 (기부금 10,000~20,000Rp)", "tip": "연못 위 사원. 일몰 시간대 방문 추천", "area": "우붓 시내", "addr": "Jl. Kajeng, Ubud"},
            {"name": "우붓 원숭이 숲", "price": "80,000Rp", "tip": "소지품 주의. 오전에 한적", "area": "우붓 시내", "addr": "Jl. Monkey Forest, Ubud", "phone": "+62 361 971 304"},
            {"name": "우붓 왕궁", "price": "무료", "tip": "저녁 전통 공연 7시. 입장료 100,000Rp", "area": "우붓 시내", "addr": "Jl. Raya Ubud No.8"},
            {"name": "아궁 라이 미술관", "price": "50,000Rp", "tip": "발리 전통 미술 컬렉션", "area": "우붓 시내", "addr": "Jl. Raya Ubud"},
        ],
        "beach": [
            {"name": "아융강 래프팅", "price": "250,000~400,000Rp", "tip": "2시간 코스. 초보 가능", "area": "우붓 외곽"},
            {"name": "천연 수영장", "price": "50,000~100,000Rp", "tip": "알링킹 폭포 근처", "area": "우붓 외곽"},
        ],
        "nature": [
            {"name": "테갈랑 라이스 테라스", "price": "15,000Rp", "tip": "새벽/오전 방문 추천", "area": "우붓 북쪽", "addr": "Jl. Raya Tegallalang"},
            {"name": "알링킹 폭포", "price": "20,000Rp", "tip": "차로 30분. 계단 많으니 편한 신발 필수", "area": "우붓 외곽"},
            {"name": "뜨갈라랑 스윙", "price": "150,000~250,000Rp", "tip": "인생샷 명소. 오전에 웨이팅 짧음", "area": "우붓 북쪽"},
            {"name": "캄포한 리지 산책", "price": "무료", "tip": "시내에서 도보 15분. 강변 절벽 코스", "area": "우붓 시내"},
        ],
        "shopping": [
            {"name": "우붓 아트 마켓", "price": "흥정 필수", "tip": "첫 가격의 30~50%. 오전에 선택 폭 넓음", "area": "우붓 시내", "addr": "Jl. Raya Ubud"},
            {"name": "마스 마을 은세공", "price": "다양", "tip": "시내보다 30~40% 저렴", "area": "마스 마을"},
            {"name": "우붓 전통 마사지", "price": "80,000~150,000Rp/1시간", "tip": "Boreh 전통 마사지 추천", "area": "우붓 시내"},
        ],
        "transport": [
            {"name": "공항→우붓", "price": "300,000Rp (90분)", "tip": "그랩 또는 사전 예약 드라이버"},
            {"name": "우붓 시내", "price": "스쿠터 80,000Rp/일", "tip": "교통체증 심하므로 오전 이동 추천"},
            {"name": "우붓→꾸따", "price": "그랩 150,000~200,000Rp (1시간)", "tip": "오후 피크 시간 피하세요"},
        ],
        "hotels": {"budget": "게스트하우스 100,000~200,000Rp/1박", "mid": "풀빌라 500,000~1,500,000Rp/1박", "high": "알리라 우붓 3,000,000Rp~/1박"},
        "price_comp": [
            {"item": "베벵길 오리구이", "local": "95,000Rp", "tour": "120,000Rp", "hotel": "180,000Rp"},
            {"item": "나시고렝", "local": "25,000Rp", "tour": "45,000Rp", "hotel": "80,000Rp"},
            {"item": "마사지 1시간", "local": "80,000Rp", "tour": "120,000Rp", "hotel": "250,000Rp"},
            {"item": "생맥주", "local": "35,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
        ],
    },
    "스미냑": {
        "desc": "트렌디한 비치 타운",
        "vibe": "비치클럽과 부티크",
        "character": "스미냑은 발리에서 가장 세련된 동네예요. 부티크숍, 비치클럽, 파인다이닝이 밀집해 있어요.",
        "transport_tip": "공항에서 30분, 그랩 150,000Rp. 교통체증 심하므로 도보/스쿠터 추천",
        "best_time": "오후 4시~7시",
        "best_season": "4~10월 건기",
        "hidden": "더블식스 비치 끝자락은 관광객 적고 선셋 포토스팟으로 최고",
        "spots": ["더블식스 비치", "포테이토 헤드", "스미냑 빌리지", "페티탕겟 사원", "쿠데타 비치클럽"],
        "airport_min": 30,
        "food": [
            {"name": "Potato Head Beach Club", "price": "음료 100,000~200,000Rp", "krw": "약 10,000~20,000원", "tip": "선셋 2시간 전 도착 추천", "area": "스미냑 비치", "must": "칵테일 + 선셋", "addr": "Jl. Petitenget No.51B", "phone": "+62 361 473 7979"},
            {"name": "La Lucciola", "price": "파스타 150,000~250,000Rp", "krw": "약 15,000~25,000원", "tip": "해변 이탈리안. 분위기 최고", "area": "스미냑 비치", "must": "해산물 파스타", "addr": "Jl. Kayu Aya", "phone": "+62 361 730 838"},
            {"name": "Warung Nia", "price": "30,000~60,000Rp", "krw": "약 3,000~6,000원", "tip": "가성비 로컬 맛집", "area": "스미냑 시내", "must": "나시캄푸르", "addr": "Jl. Kayu Aya No.2"},
            {"name": "Sisterfields", "price": "브런치 80,000~150,000Rp", "krw": "약 8,000~15,000원", "tip": "호주식 브런치. 주말 웨이팅", "area": "스미냑 시내", "must": "에그 베네딕트", "addr": "Jl. Kayu Cendana No.7"},
            {"name": "Motel Mexicola", "price": "칵테일 80,000~150,000Rp", "krw": "약 8,000~15,000원", "tip": "멕시칸 바. 밤에는 파티 분위기", "area": "스미냑 시내", "must": "타코 + 마가리타", "addr": "Jl. Kayu Jati No.9X"},
            {"name": "Sarong", "price": "메인 150,000~300,000Rp", "krw": "약 15,000~30,000원", "tip": "아시안 퓨전 파인다이닝", "area": "스미냑 시내", "must": "아시안 타파스", "addr": "Jl. Petitenget No.19X"},
        ],
        "culture": [
            {"name": "페티탕겟 사원", "price": "무료 (기부금)", "tip": "해변 사원. 선셋 시간대 추천", "area": "스미냑 비치", "addr": "Jl. Petitenget"},
            {"name": "스미냑 빌리지", "price": "무료", "tip": "전통 마을 산책", "area": "스미냑 시내"},
        ],
        "beach": [
            {"name": "더블식스 비치", "price": "무료", "tip": "선셋 포토스팟. 비치클럽 다수", "area": "스미냑"},
            {"name": "스미냑 비치 서핑", "price": "150,000~250,000Rp/1회", "tip": "초보 강습 가능", "area": "스미냑"},
            {"name": "쿠데타 비치클럽", "price": "음료 80,000~150,000Rp", "tip": "선베드 무료. 최소 음료 1잔", "area": "스미냑 비치"},
        ],
        "nature": [{"name": "해변 산책로", "price": "무료", "tip": "더블식스~포테이토 헤드 약 2km", "area": "스미냑"}],
        "shopping": [
            {"name": "스미냑 빌리지 쇼핑", "price": "다양", "tip": "부티크숍 밀집. 세일 11~12월", "area": "스미냑 시내"},
            {"name": "스미냑 스파", "price": "150,000~400,000Rp/1시간", "tip": "Spring Spa, Bodyworks 추천", "area": "스미냑 시내"},
        ],
        "transport": [
            {"name": "공항→스미냑", "price": "150,000Rp (30분)", "tip": "그랩 추천"},
            {"name": "스미냑 시내", "price": "도보 가능", "tip": "교통체증 심하므로 도보/스쿠터"},
        ],
        "hotels": {"budget": "게스트하우스 150,000~300,000Rp/1박", "mid": "부티크 호텔 500,000~1,500,000Rp/1박", "high": "위 발리 5,000,000Rp~/1박"},
        "price_comp": [
            {"item": "비치클럽 음료", "local": "100,000Rp", "tour": "150,000Rp", "hotel": "200,000Rp"},
            {"item": "파스타", "local": "150,000Rp", "tour": "180,000Rp", "hotel": "250,000Rp"},
            {"item": "로컬 음식", "local": "30,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
            {"item": "마사지 1시간", "local": "80,000Rp", "tour": "150,000Rp", "hotel": "300,000Rp"},
        ],
    },
    "꾸따": {
        "desc": "발리 최초의 관광지, 서핑의 성지",
        "vibe": "서핑과 파티",
        "character": "꾸따는 발리에서 가장 활기찬 해변 도시예요. 서핑, 쇼핑, 나이트라이프가 모두 있어요.",
        "transport_tip": "공항에서 15분, 그랩 100,000Rp. 첫날이나 마지막 날 방문하기 좋아요",
        "best_time": "오후 4시~6시",
        "best_season": "4~10월 건기",
        "hidden": "꾸따 북쪽 레기안 비치는 꾸보다 한적하고 서핑 포인트도 좋아요",
        "spots": ["꾸따 비치", "워터밤 파크", "비치워크 쇼핑몰", "꾸따 아트 마켓", "서핑 포인트"],
        "airport_min": 15,
        "food": [
            {"name": "Warung Murah", "price": "나시고렝 20,000~35,000Rp", "krw": "약 2,000~3,500원", "tip": "꾸따 대표 저렴한 로컬 맛집", "area": "꾸따 시내", "must": "나시고렝 스페셜", "addr": "Jl. Poppies Lane I, Kuta"},
            {"name": "Made's Warung", "price": "현지 음식 40,000~80,000Rp", "krw": "약 4,000~8,000원", "tip": "1969년부터 운영된 전통 맛집", "area": "꾸따 시내", "must": "나시짬뿌르", "addr": "Jl. Raya Seminyak No.96", "phone": "+62 361 732 171"},
            {"name": "Hard Rock Cafe Bali", "price": "버거 120,000~180,000Rp", "krw": "약 12,000~18,000원", "tip": "꾸따 비치 앞. 라이브 음악", "area": "꾸따 비치", "must": "레전더리 버거", "addr": "Jl. Pantai, Kuta", "phone": "+62 361 755 663"},
            {"name": "Poppies Restaurant", "price": "파스타 80,000~150,000Rp", "krw": "약 8,000~15,000원", "tip": "정원 분위기의 레스토랑", "area": "팝피스 레인", "must": "해산물 파스타", "addr": "Jl. Poppies Lane I, Kuta"},
            {"name": "Bamboo Corner", "price": "현지 음식 25,000~50,000Rp", "krw": "약 2,500~5,000원", "tip": "가성비 로컬 맛집", "area": "꾸따 시내", "must": "나시캄푸르", "addr": "Jl. Poppies Lane II, Kuta"},
        ],
        "culture": [
            {"name": "꾸따 아트 마켓", "price": "무료 입장", "tip": "기념품 쇼핑 명소. 흥정 필수", "area": "꾸따 시내"},
            {"name": "워터밤 발리", "price": "535,000Rp", "tip": "발리 최대 워터파크", "area": "꾸따", "addr": "Jl. Kartika, Tuban"},
        ],
        "beach": [
            {"name": "꾸따 비치", "price": "무료", "tip": "서핑 강습 가능. 선셋 포토스팟", "area": "꾸따"},
            {"name": "레기안 비치", "price": "무료", "tip": "꾸보다 한적한 해변", "area": "레기안"},
            {"name": "꾸따 서핑 강습", "price": "150,000~250,000Rp/1회", "tip": "보드 포함. 2시간 강습", "area": "꾸따 비치"},
        ],
        "nature": [],
        "shopping": [
            {"name": "비치워크 쇼핑몰", "price": "다양", "tip": "꾸따 최대 쇼핑몰", "area": "꾸따 비치", "addr": "Jl. Pantai Kuta"},
            {"name": "Discovery Mall", "price": "다양", "tip": "로컬 브랜드 위주", "area": "꾸따"},
            {"name": "꾸따 마사지", "price": "60,000~100,000Rp/1시간", "tip": "해변 마사지가 가장 저렴", "area": "꾸따 비치"},
        ],
        "transport": [
            {"name": "공항→꾸따", "price": "100,000Rp (15분)", "tip": "공항에서 가장 가까운 관광지"},
            {"name": "꾸따 시내", "price": "도보 가능", "tip": "꾸따는 도보 이동 가능"},
        ],
        "hotels": {"budget": "게스트하우스 80,000~150,000Rp/1박", "mid": "비치 호텔 300,000~800,000Rp/1박", "high": "하드락 호텔 1,500,000Rp~/1박"},
        "price_comp": [
            {"item": "서핑 강습 (1회)", "local": "150,000Rp", "tour": "250,000Rp", "hotel": "350,000Rp"},
            {"item": "나시고렝", "local": "20,000Rp", "tour": "40,000Rp", "hotel": "70,000Rp"},
            {"item": "맥주", "local": "35,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
            {"item": "마사지 1시간", "local": "60,000Rp", "tour": "100,000Rp", "hotel": "200,000Rp"},
        ],
    },
    "사누르": {
        "desc": "조용한 해변 휴양지",
        "vibe": "가족 휴양",
        "character": "사누르는 꾸따나 스미냑보다 조용하고 여유로운 해변 도시예요. 가족 여행객이 많아요.",
        "transport_tip": "공항에서 30분, 그랩 150,000Rp. 자전거 대여 50,000Rp/일",
        "best_time": "오전 6시~9시",
        "best_season": "4~10월 건기",
        "hidden": "사누르 비치 산책로는 5km로 자전거 타기 좋고, 끝자락에 현지 어부 마을이 있어요",
        "spots": ["사누르 비치", "사누르 아트 마켓", "빠당 라마 사원", "발리 사파리", "사누르 나이트 마켓"],
        "airport_min": 30,
        "food": [
            {"name": "Warung Mak Beng", "price": "생선튀김 세트 35,000Rp", "krw": "약 3,500원", "tip": "줄 서서 먹는 집. 생선튀김+나시+삼발이 세트", "area": "사누르 시내", "must": "생선튀김 세트", "addr": "Jl. Hang Tuah No.45, Sanur", "phone": "+62 361 282 633"},
            {"name": "Massimo", "price": "파스타 100,000~180,000Rp", "krw": "약 10,000~18,000원", "tip": "사누르 최고의 이탈리안. 점심 세트 메뉴 추천", "area": "사누르 시내", "must": "트러플 파스타", "addr": "Jl. Danau Tamblingan No.228", "phone": "+62 361 288 133"},
            {"name": "Cafe Batu Jimbar", "price": "브런치 70,000~130,000Rp", "krw": "약 7,000~13,000원", "tip": "정원 분위기 카페. 아침 식사 추천", "area": "사누르 시내", "must": "발리니즈 브렉퍼스트", "addr": "Jl. Danau Tamblingan No.75A"},
            {"name": "Three Monkeys Sanur", "price": "브런치 60,000~120,000Rp", "krw": "약 6,000~12,000원", "tip": "강변 뷰 카페. 분위기 좋음", "area": "사누르 시내", "must": "스무디볼", "addr": "Jl. Danau Tamblingan"},
        ],
        "culture": [
            {"name": "빠당 라마 사원", "price": "무료 (기부금)", "tip": "사누르 대표 사원", "area": "사누르 시내"},
            {"name": "사누르 아트 마켓", "price": "무료 입장", "tip": "기념품 쇼핑. 흥정 필수", "area": "사누르 시내"},
        ],
        "beach": [
            {"name": "사누르 비치", "price": "무료", "tip": "일출 명소. 오전 5:30까지 도착", "area": "사누르"},
            {"name": "사누르 비치 산책로", "price": "무료", "tip": "5km 해변 산책로. 자전거 추천", "area": "사누르"},
        ],
        "nature": [
            {"name": "발리 사파리 & 마린 파크", "price": "750,000Rp", "tip": "가족 여행객 추천. 사파리 + 워터파크", "area": "사누르 외곽", "addr": "Jl. Bypass Prof. Dr. Ida Bagus Mantra"},
        ],
        "shopping": [
            {"name": "사누르 나이트 마켓", "price": "다양", "tip": "저녁 6시부터. 로컬 음식과 기념품", "area": "사누르 시내"},
            {"name": "사누르 스파", "price": "100,000~250,000Rp/1시간", "tip": "스미냑보다 30~40% 저렴", "area": "사누르 시내"},
        ],
        "transport": [
            {"name": "공항→사누르", "price": "150,000Rp (30분)", "tip": "그랩 추천"},
            {"name": "사누르 시내", "price": "자전거 50,000Rp/일", "tip": "평지라 자전거 이동 편리"},
        ],
        "hotels": {"budget": "게스트하우스 100,000~250,000Rp/1박", "mid": "비치 리조트 600,000~1,500,000Rp/1박", "high": "하얏트 리젠시 2,500,000Rp~/1박"},
        "price_comp": [
            {"item": "생선튀김 세트", "local": "35,000Rp", "tour": "60,000Rp", "hotel": "100,000Rp"},
            {"item": "파스타", "local": "100,000Rp", "tour": "130,000Rp", "hotel": "200,000Rp"},
            {"item": "자전거 대여", "local": "50,000Rp", "tour": "80,000Rp", "hotel": "120,000Rp"},
            {"item": "마사지 1시간", "local": "100,000Rp", "tour": "150,000Rp", "hotel": "250,000Rp"},
        ],
    },
    "누사두아": {
        "desc": "고급 리조트 지역",
        "vibe": "리조트와 해변",
        "character": "누사두아는 발리에서 가장 고급스러운 리조트 지역이예요. 깨끗한 해변과 프리미엄 시설이 장점이에요.",
        "transport_tip": "공항에서 30분, 그랩 150,000Rp. 리조트 내 셔틀버스 무료",
        "best_time": "오전 8시~11시",
        "best_season": "4~10월 건기",
        "hidden": "블로우 홀 근처 절벽 카페에서 보는 인도양 뷰가 환상적이에요",
        "spots": ["누사두아 비치", "발리 컬렉션 쇼핑몰", "워터밤 파크", "블로우 홀", "파라다이스 극장"],
        "airport_min": 30,
        "food": [
            {"name": "Bumbu Bali", "price": "현지 음식 80,000~150,000Rp", "krw": "약 8,000~15,000원", "tip": "발리 전통 요리 전문. 쿠킹 클래스도 운영", "area": "누사두아", "must": "발리니즈 세트", "addr": "Jl. Pratama, Tanjung Benoa", "phone": "+62 361 774 111"},
            {"name": "Warung Dobiel", "price": "나시캄푸르 25,000~45,000Rp", "krw": "약 2,500~4,500원", "tip": "누사두아에서 가성비 최고 로컬 맛집", "area": "누사두아", "must": "나시캄푸르", "addr": "Jl. Pantai Mengiat"},
            {"name": "Kayuputi Restaurant", "price": "메인 200,000~400,000Rp", "krw": "약 20,000~40,000원", "tip": "리조트 내 파인다이닝. 오션뷰", "area": "누사두아", "must": "해산물 플래터", "addr": "St. Regis Bali Resort"},
            {"name": "Piasan Restaurant", "price": "메인 150,000~300,000Rp", "krw": "약 15,000~30,000원", "tip": "이탈리안 + 아시안 퓨전", "area": "누사두아", "must": "랍스터 파스타", "addr": "Jl. Raya Nusa Dua"},
        ],
        "culture": [
            {"name": "파라다이스 극장 발룽안 공연", "price": "250,000~500,000Rp", "tip": "발리 전통 서사시 공연. 예약 추천", "area": "누사두아", "addr": "Jl. Nusa Dua"},
        ],
        "beach": [
            {"name": "누사두아 비치", "price": "무료", "tip": "깨끗하고 조용한 해변. 리조트 전용 구역도 있음", "area": "누사두아"},
            {"name": "블로우 홀", "price": "무료", "tip": "파도가 절벽 구멍으로 분출하는 자연 현상", "area": "누사두아 남쪽"},
            {"name": "워터 스포츠 (제트스키)", "price": "350,000~600,000Rp", "tip": "탄중 베노아 비치에서 다양한 수상 스포츠", "area": "탄중 베노아"},
        ],
        "nature": [
            {"name": "블로우 홀 & 판다와 비치", "price": "무료", "tip": "절벽 아래 숨겨진 해변", "area": "누사두아 남쪽"},
        ],
        "shopping": [
            {"name": "발리 컬렉션 쇼핑몰", "price": "다양", "tip": "누사두아 유일의 쇼핑몰. 레스토랑+카페", "area": "누사두아", "addr": "Kawasan Pariwisata BTDC"},
            {"name": "누사두아 스파", "price": "200,000~500,000Rp/1시간", "tip": "리조트급 스파 시설", "area": "누사두아"},
        ],
        "transport": [
            {"name": "공항→누사두아", "price": "150,000Rp (30분)", "tip": "그랩 추천"},
            {"name": "누사두아 시내", "price": "리조트 셔틀 무료", "tip": "리조트 객이면 셔틀 활용"},
        ],
        "hotels": {"budget": "게스트하우스 200,000~400,000Rp/1박", "mid": "비치 리조트 800,000~2,000,000Rp/1박", "high": "세인트 리지스 5,000,000Rp~/1박"},
        "price_comp": [
            {"item": "발리니즈 세트", "local": "80,000Rp", "tour": "120,000Rp", "hotel": "200,000Rp"},
            {"item": "제트스키", "local": "350,000Rp", "tour": "500,000Rp", "hotel": "600,000Rp"},
            {"item": "스파 1시간", "local": "200,000Rp", "tour": "300,000Rp", "hotel": "500,000Rp"},
            {"item": "맥주", "local": "40,000Rp", "tour": "60,000Rp", "hotel": "100,000Rp"},
        ],
    },
    "울루와뚜": {
        "desc": "절벽 위의 사원과 서핑",
        "vibe": "절벽과 서핑",
        "character": "울루와뚜는 발리 남부 끝자락의 절벽 지역이에요. 울루와뚜 사원의 일몰이 유명하고, 세계적 수준의 서핑 포인트가 있어요.",
        "transport_tip": "공항에서 40분, 그랩 200,000Rp. 절벽 지역이라 이동 시간 여유 있게 잡으세요",
        "best_time": "오후 4시~6시",
        "best_season": "4~10월 건기",
        "hidden": "짐바란 비치의 해산물 바비큐는 일몰과 함께 먹으면 분위기 최고예요",
        "spots": ["울루와뚜 사원", "울루와뚜 비치", "짐바란 비치", "블루포인트 비치", "판다와 비치"],
        "airport_min": 40,
        "food": [
            {"name": "짐바란 해산물 바비큐", "price": "해산물 세트 150,000~400,000Rp", "krw": "약 15,000~40,000원", "tip": "해변에서 일몰과 함께 먹는 해산물 BBQ", "area": "짐바란 비치", "must": "랍스터 + 새우 세트", "addr": "Jl. Pantai Jimbaran"},
            {"name": "Single Fin", "price": "음료 80,000~150,000Rp", "krw": "약 8,000~15,000원", "tip": "절벽 위 바. 서퍼들이 모이는 곳", "area": "울루와뚜", "must": "선셋 칵테일", "addr": "Jl. Mamo, Uluwatu", "phone": "+62 361 769 941"},
            {"name": "Warung Sego Njamoer", "price": "나시 20,000~40,000Rp", "krw": "약 2,000~4,000원", "tip": "짐바란 로컬 맛집. 가성비 최고", "area": "짐바란", "must": "나시캄푸르"},
            {"name": "El Kabron", "price": "메인 150,000~300,000Rp", "krw": "약 15,000~30,000원", "tip": "절벽 위 스페인 레스토랑. 뷰가 환상적", "area": "울루와뚜", "must": "빠에야 + 선셋", "addr": "Jl. Pantai Cemongkak"},
        ],
        "culture": [
            {"name": "울루와뚜 사원", "price": "50,000Rp", "tip": "일몰 시간대 케착 공연 추천 (100,000Rp)", "area": "울루와뚜", "addr": "Pecatu, Kuta Selatan"},
            {"name": "울루와뚜 케착 공연", "price": "100,000Rp", "tip": "일몰 시간(오후 6시)에 절벽 위에서 열리는 전통 dance", "area": "울루와뚜 사원"},
        ],
        "beach": [
            {"name": "울루와뚜 비치 (수루파단)", "price": "무료", "tip": "절벽 아래 숨겨진 해변. 계단 내려가야 함", "area": "울루와뚜"},
            {"name": "블루포인트 비치", "price": "무료", "tip": "서핑 포인트. 중급자 이상 추천", "area": "울루와뚜"},
            {"name": "판다와 비치", "price": "15,000Rp", "tip": "절벽 아래 깨끗한 해변", "area": "울루와뚜 남쪽"},
            {"name": "짐바란 비치", "price": "무료", "tip": "해산물 BBQ + 일몰", "area": "짐바란"},
        ],
        "nature": [],
        "shopping": [],
        "transport": [
            {"name": "공항→울루와뚜", "price": "200,000Rp (40분)", "tip": "그랩 추천"},
            {"name": "울루와뚜 시내", "price": "스쿠터 80,000Rp/일", "tip": "절벽 지역이라 도보 어려움"},
        ],
        "hotels": {"budget": "게스트하우스 150,000~300,000Rp/1박", "mid": "클리프 리조트 800,000~2,000,000Rp/1박", "high": "알리라 울루와뚜 4,000,000Rp~/1박"},
        "price_comp": [
            {"item": "해산물 BBQ 세트", "local": "150,000Rp", "tour": "250,000Rp", "hotel": "400,000Rp"},
            {"item": "케착 공연", "local": "100,000Rp", "tour": "150,000Rp", "hotel": "200,000Rp"},
            {"item": "서핑 강습", "local": "200,000Rp", "tour": "350,000Rp", "hotel": "500,000Rp"},
            {"item": "맥주", "local": "35,000Rp", "tour": "60,000Rp", "hotel": "100,000Rp"},
        ],
    },
    "짠디다사": {
        "desc": "조용한 어촌 마을",
        "vibe": "힐링과 다이빙",
        "character": "짠디다사는 발리 동부의 조용한 어촌 마을이에요. 다이빙과 스노클링 명소로 유명해요.",
        "transport_tip": "공항에서 2시간, 그랩 400,000Rp. 우붓에서 1시간 30분",
        "best_time": "오전 7시~10시",
        "best_season": "4~10월 건기",
        "hidden": "아메드 비치에서 보는 일출과 아궁 화산 뷰가 환상적이에요",
        "spots": ["짠디다사 비치", "아꿍 화산", "베사키 사원", "티르타강가", "아메드 비치"],
        "airport_min": 120,
        "food": [
            {"name": "Warung Padang Kecag", "price": "나시 20,000~40,000Rp", "krw": "약 2,000~4,000원", "tip": "짠디다사 로컬 맛집. 신선한 해산물", "area": "짠디다사", "must": "생선구이", "addr": "Jl. Raya Candidasa"},
            {"name": "Vincent's", "price": "메인 80,000~150,000Rp", "krw": "약 8,000~15,000원", "tip": "해변 레스토랑. 유럽식 + 현지식", "area": "짠디다사", "must": "해산물 파스타", "addr": "Jl. Raya Candidasa"},
            {"name": "Lega's Warung", "price": "나시 25,000~50,000Rp", "krw": "약 2,500~5,000원", "tip": "가성비 로컬 맛집", "area": "짠디다사", "must": "나시캄푸르"},
        ],
        "culture": [
            {"name": "베사키 사원 (어머니 사원)", "price": "75,000Rp", "tip": "발리에서 가장 중요한 사원. 아꿍 화산 기슭에 위치", "area": "아społ", "addr": "Besakih, Karangasem"},
            {"name": "티르타강가", "price": "15,000Rp", "tip": "신성한 분수와 수영장. 물놀이 가능", "area": "짠디다사 근처"},
        ],
        "beach": [
            {"name": "짠디다사 비치", "price": "무료", "tip": "조용한 해변. 스노클링 가능", "area": "짠디다사"},
            {"name": "아메드 비치", "price": "무료", "tip": "다이빙 명소. 일출 포인트", "area": "아메드"},
            {"name": "블루 라군 비치", "price": "무료", "tip": "스노클링 포인트. 산호가 예뻐요", "area": "아메드"},
        ],
        "nature": [
            {"name": "아꿍 화산 트레킹", "price": "450,000~700,000Rp", "tip": "새벽 2시 출발. 일출 트레킹", "area": "아 وحت"},
        ],
        "shopping": [],
        "transport": [
            {"name": "공항→짠디다사", "price": "400,000Rp (2시간)", "tip": "그랩 또는 사전 예약"},
            {"name": "짠디다사→아메드", "price": "100,000Rp (30분)", "tip": "스쿠터 렌트 추천"},
        ],
        "hotels": {"budget": "게스트하우스 100,000~200,000Rp/1박", "mid": "비치 호텔 400,000~1,000,000Rp/1박", "high": "피타 마하 3,000,000Rp~/1박"},
        "price_comp": [
            {"item": "생선구이", "local": "25,000Rp", "tour": "50,000Rp", "hotel": "100,000Rp"},
            {"item": "다이빙 (1회)", "local": "500,000Rp", "tour": "800,000Rp", "hotel": "1,000,000Rp"},
            {"item": "베사키 사원 입장", "local": "75,000Rp", "tour": "100,000Rp", "hotel": "150,000Rp"},
            {"item": "맥주", "local": "30,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
        ],
    },
    "로비나": {
        "desc": "북부의 조용한 해변 도시",
        "vibe": "돌고래와 온천",
        "character": "로비나는 발리 북부의 조용한 해변 도시예요. 돌고래 투어와 온천이 유명해요.",
        "transport_tip": "공항에서 3시간, 그랩 600,000Rp. 우붓에서 2시간 30분",
        "best_time": "오전 6시~9시",
        "best_season": "4~10월 건기",
        "hidden": "반자르 온천은 현지인들이 많이 가는 곳으로, 관광객보다 저렴하고 진짜 온천 분위기를 느낄 수 있어요",
        "spots": ["로비나 비치 (돌고래 투어)", "반자르 온천", "기트기트 폭포", "발리 국립공원", "브둘루 사원"],
        "airport_min": 180,
        "food": [
            {"name": "Warung Ibu Made", "price": "나시 20,000~40,000Rp", "krw": "약 2,000~4,000원", "tip": "로비나 로컬 맛집. 신선한 해산물", "area": "로비나", "must": "생선구이", "addr": "Jl. Raya Lovina"},
            {"name": "Kakatua Restaurant", "price": "메인 60,000~120,000Rp", "krw": "약 6,000~12,000원", "tip": "해변 레스토랑. 일몰 뷰", "area": "로비나 비치", "must": "해산물 BBQ", "addr": "Jl. Raya Lovina"},
            {"name": "Sea Breeze Cafe", "price": "브런치 50,000~100,000Rp", "krw": "약 5,000~10,000원", "tip": "아침 식사 추천", "area": "로비나", "must": "팬케이크"},
        ],
        "culture": [
            {"name": "브둘루 사원", "price": "무료 (기부금)", "tip": "로비나 근처 해변 사원", "area": "로비나"},
        ],
        "beach": [
            {"name": "로비나 비치 (돌고래 투어)", "price": "100,000~150,000Rp", "tip": "새벽 6시 출발. 돌고래 관찰", "area": "로비나"},
            {"name": "로비나 비치 산책", "price": "무료", "tip": "검은 모래 해변", "area": "로비나"},
        ],
        "nature": [
            {"name": "반자르 온천", "price": "100,000Rp", "tip": "뜨거운 유황 온천. 수영복 필수", "area": "반자르", "addr": "Banjar, Buleleng"},
            {"name": "기트기트 폭포", "price": "20,000Rp", "tip": "발리에서 가장 높은 폭포. 계단 많음", "area": "로비나 외곽"},
            {"name": "발리 바랏 국립공원", "price": "200,000Rp", "tip": "야생 동물 관찰. 가이드 추천", "area": "서쪽 끝"},
        ],
        "shopping": [],
        "transport": [
            {"name": "공항→로비나", "price": "600,000Rp (3시간)", "tip": "우붓 경유 추천"},
            {"name": "로비나 시내", "price": "스쿠터 70,000Rp/일", "tip": "한적한 지역이라 이동 편리"},
        ],
        "hotels": {"budget": "게스트하우스 80,000~150,000Rp/1박", "mid": "비치 호텔 300,000~800,000Rp/1박", "high": "로비나 비치 리조트 1,500,000Rp~/1박"},
        "price_comp": [
            {"item": "돌고래 투어", "local": "100,000Rp", "tour": "200,000Rp", "hotel": "300,000Rp"},
            {"item": "반자르 온천", "local": "100,000Rp", "tour": "150,000Rp", "hotel": "200,000Rp"},
            {"item": "나시", "local": "20,000Rp", "tour": "40,000Rp", "hotel": "70,000Rp"},
            {"item": "맥주", "local": "30,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
        ],
    },
    "킨타마니": {
        "desc": "화산과 호수의 고원",
        "vibe": "화산 트레킹",
        "character": "킨타마니는 발리 중부의 고원 지역이에요. 바투르 화산과 호수의 장관이 펼쳐져요.",
        "transport_tip": "공항에서 2시간 30분, 그랩 500,000Rp. 우붓에서 1시간 30분",
        "best_time": "오전 5시~8시",
        "best_season": "4~10월 건기",
        "hidden": "바투르 호수 온천은 화산 트레킹 후 몸을 녹이기에 딱 좋아요",
        "spots": ["바투르 화산", "바투르 호수", "킨타마니 전망대", "뜨걀라랑 라이스 테라스", "뜨리뜨 에פק 사원"],
        "airport_min": 150,
        "food": [
            {"name": "Grand Puncak Resto", "price": "뷔페 100,000~150,000Rp", "krw": "약 10,000~15,000원", "tip": "바투르 호수 전망 뷔페", "area": "킨타마니", "must": "인도네시안 뷔페", "addr": "Kintamani"},
            {"name": "Warung Seni Kintamani", "price": "나시 25,000~50,000Rp", "krw": "약 2,500~5,000원", "tip": "로컬 맛집. 저렴한 가격", "area": "킨타마니", "must": "나시캄푸르"},
        ],
        "culture": [
            {"name": "뜨리뜨 에פק 사원", "price": "75,000Rp", "tip": "화산 호수 옆 신성한 사원", "area": "킨타마니"},
            {"name": "뜨걀라랑 라이스 테라스", "price": "15,000Rp", "tip": "우붓 근처지만 킨타마니 코스와 연계 가능", "area": "뜨걀라랑"},
        ],
        "beach": [],
        "nature": [
            {"name": "바투르 화산 트레킹", "price": "450,000~700,000Rp", "tip": "새벽 2시 출발. 일출 트레킹. 가이드 필수", "area": "킨타마니"},
            {"name": "바투르 호수", "price": "무료", "tip": "화산 호수. 카약 가능", "area": "킨타마니"},
            {"name": "킨타마니 전망대", "price": "50,000Rp", "tip": "바투르 화산+호수 파노라마", "area": "킨타마니"},
        ],
        "shopping": [],
        "transport": [
            {"name": "공항→킨타마니", "price": "500,000Rp (2시간 30분)", "tip": "우붓 경유 추천"},
            {"name": "킨타마니 시내", "price": "전용 차량 필요", "tip": "대중교통 없음. 드라이버 고용 추천"},
        ],
        "hotels": {"budget": "게스트하우스 150,000~300,000Rp/1박", "mid": "산장 호텔 400,000~1,000,000Rp/1박", "high": "킨타마니 리조트 2,000,000Rp~/1박"},
        "price_comp": [
            {"item": "화산 트레킹", "local": "450,000Rp", "tour": "700,000Rp", "hotel": "900,000Rp"},
            {"item": "뷔페", "local": "100,000Rp", "tour": "150,000Rp", "hotel": "200,000Rp"},
            {"item": "전망대 입장", "local": "50,000Rp", "tour": "75,000Rp", "hotel": "100,000Rp"},
            {"item": "맥주", "local": "35,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
        ],
    },
    "타나롯": {
        "desc": "바다 위 사원의 도시",
        "vibe": "일몰과 사원",
        "character": "타나롯은 발리에서 가장 사진이 잘 나오는 사원이 있는 곳이에요. 바다 위 우뚝 선 사원의 일몰이 장관이에요.",
        "transport_tip": "공항에서 90분, 그랩 250,000Rp. 우붓에서 40분",
        "best_time": "오후 4시~6시",
        "best_season": "4~10월 건기",
        "hidden": "바투 볼롱 사원은 타나롯보다 관광객 적고 일몰 뷰가 더 좋아요",
        "spots": ["타나롯 사원", "일몰 포인트", "바투 볼롱 사원", "잘란 라이스 테라스", "타나롯 시장"],
        "airport_min": 90,
        "food": [
            {"name": "Warung D'Sawah", "price": "나시 25,000~50,000Rp", "krw": "약 2,500~5,000원", "tip": "논뷰 맛집. 조용한 분위기", "area": "타나롯", "must": "나시캄푸르", "addr": "Jl. Raya Tanah Lot"},
            {"name": "Tanah Lot Sunset Restaurant", "price": "메인 80,000~150,000Rp", "krw": "약 8,000~15,000원", "tip": "타나롯 사원이 보이는 레스토랑", "area": "타나롯", "must": "해산물 + 선셋", "addr": "Tanah Lot"},
        ],
        "culture": [
            {"name": "타나롯 사원", "price": "60,000Rp", "tip": "일몰 시간대 방문 추천. 조수 시간 확인 필수", "area": "타나롯", "addr": "Beraban, Kediri"},
            {"name": "바투 볼롱 사원", "price": "30,000Rp", "tip": "타나롯보다 한적한 일몰 명소", "area": "타나롯 근처"},
        ],
        "beach": [
            {"name": "타나롯 해변 산책", "price": "무료", "tip": "사원 주변 해변 산책", "area": "타나롯"},
        ],
        "nature": [
            {"name": "잘란 라이스 테라스", "price": "무료", "tip": "타나롯 근처 숨은 명소", "area": "타나롯 근처"},
        ],
        "shopping": [
            {"name": "타나롯 시장", "price": "다양", "tip": "사원 입구 기념품 시장", "area": "타나롯"},
        ],
        "transport": [
            {"name": "공항→타나롯", "price": "250,000Rp (90분)", "tip": "우붓 경유 추천"},
            {"name": "타나롯 시내", "price": "전용 차량 필요", "tip": "대중교통 없음"},
        ],
        "hotels": {"budget": "게스트하우스 100,000~200,000Rp/1박", "mid": "리조트 500,000~1,200,000Rp/1박", "high": "알리라 타나롯 4,000,000Rp~/1박"},
        "price_comp": [
            {"item": "타나롯 사원 입장", "local": "60,000Rp", "tour": "100,000Rp", "hotel": "150,000Rp"},
            {"item": "나시", "local": "25,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
            {"item": "기념품", "local": "30,000Rp", "tour": "80,000Rp", "hotel": "150,000Rp"},
            {"item": "맥주", "local": "35,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
        ],
    },
    "베두굴": {
        "desc": "호수 위의 사원",
        "vibe": "고원과 정원",
        "character": "베두굴은 발리 고원 지역이에요. 울룬 다누 브라탄 사원과 보타닉 가든이 유명해요.",
        "transport_tip": "공항에서 2시간, 그랩 400,000Rp. 우붓에서 1시간 30분",
        "best_time": "오전 8시~11시",
        "best_season": "4~10월 건기",
        "hidden": "발리 보타닉 가든은 오전에 가면 안개 속 정원 분위기가 환상적이에요",
        "spots": ["울룬 다누 브라탄 사원", "브라탄 호수", "발리 보타닉 가든", "몽키 포레스트", "베두굴 전통 시장"],
        "airport_min": 120,
        "food": [
            {"name": "Warung Classic", "price": "나시 20,000~40,000Rp", "krw": "약 2,000~4,000원", "tip": "베두굴 로컬 맛집", "area": "베두굴", "must": "나시캄푸르", "addr": "Jl. Raya Bedugul"},
            {"name": "Bali Strawberry", "price": "디저트 30,000~60,000Rp", "krw": "약 3,000~6,000원", "tip": "딸기 농장 카페. 직접 딸기 따기 체험 가능", "area": "베두굴", "must": "딸기 스무디", "addr": "Jl. Raya Bedugul"},
        ],
        "culture": [
            {"name": "울룬 다누 브라탄 사원", "price": "75,000Rp", "tip": "호수 위 사원. 오전에 안개 없이 깨끗한 뷰", "area": "베두굴", "addr": "Danau Beratan, Candikuning"},
        ],
        "beach": [],
        "nature": [
            {"name": "발리 보타닉 가든", "price": "30,000Rp", "tip": "열대 식물원. 2~3시간 소요", "area": "베두굴", "addr": "Jl. Kebun Raya, Candikuning"},
            {"name": "몽키 포레스트 (알라스 케다똔)", "price": "20,000Rp", "tip": "베두굴 원숭이 숲", "area": "베두굴"},
            {"name": "브라탄 호수", "price": "무료", "tip": "카약 또는 보트 투어 가능", "area": "베두굴"},
        ],
        "shopping": [
            {"name": "베두굴 전통 시장", "price": "다양", "tip": "신선한 과일과 채소. 딸기가 유명", "area": "베두굴", "addr": "Jl. Raya Bedugul"},
        ],
        "transport": [
            {"name": "공항→베두굴", "price": "400,000Rp (2시간)", "tip": "우붓 경유 추천"},
            {"name": "베두굴 시내", "price": "전용 차량 필요", "tip": "대중교통 없음"},
        ],
        "hotels": {"budget": "게스트하우스 100,000~200,000Rp/1박", "mid": "산장 호텔 300,000~800,000Rp/1박", "high": "문락 리조트 1,500,000Rp~/1박"},
        "price_comp": [
            {"item": "브라탄 사원 입장", "local": "75,000Rp", "tour": "100,000Rp", "hotel": "150,000Rp"},
            {"item": "보타닉 가든", "local": "30,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
            {"item": "나시", "local": "20,000Rp", "tour": "40,000Rp", "hotel": "70,000Rp"},
            {"item": "딸기 스무디", "local": "30,000Rp", "tour": "50,000Rp", "hotel": "80,000Rp"},
        ],
    },
}
